export const STORAGE_KEY = "SHOPPING_ITEMS";
export const STORE_KEY = "SELECTED_STORE";

export const stores = [
  "Lidl",
  "Jumbo",
  "Albert Heijn",
];

export const storeRoutes = {
  Lidl: [
    "Groente en fruit",
    "Brood",
    "Ontbijt",
    "Conserven",
    "Pasta en rijst",
    "Sauzen en kruiden",
    "Drinken",
    "Snacks en snoep",
    "Koeling en zuivel",
    "Vlees en vis",
    "Diepvries",
    "Huishouden",
    "Overig",
  ],

  Jumbo: [
    "Groente en fruit",
    "Brood",
    "Vlees en vis",
    "Koeling en zuivel",
    "Ontbijt",
    "Pasta en rijst",
    "Conserven",
    "Sauzen en kruiden",
    "Snacks en snoep",
    "Drinken",
    "Diepvries",
    "Huishouden",
    "Overig",
  ],

  "Albert Heijn": [
    "Groente en fruit",
    "Brood",
    "Vlees en vis",
    "Koeling en zuivel",
    "Ontbijt",
    "Pasta en rijst",
    "Sauzen en kruiden",
    "Conserven",
    "Snacks en snoep",
    "Drinken",
    "Diepvries",
    "Huishouden",
    "Overig",
  ],
};

export const categoryIcons = {
  "Groente en fruit": "leaf-outline",
  Brood: "restaurant-outline",
  Ontbijt: "sunny-outline",
  Conserven: "cube-outline",
  "Pasta en rijst": "fast-food-outline",
  "Sauzen en kruiden": "flask-outline",
  Drinken: "water-outline",
  "Snacks en snoep": "ice-cream-outline",
  "Koeling en zuivel": "snow-outline",
  "Vlees en vis": "fish-outline",
  Diepvries: "snow-outline",
  Huishouden: "home-outline",
  Overig: "basket-outline",
};

export const categoryKeywords = {
  "Groente en fruit": [
    "appel",
    "appels",
    "banaan",
    "bananen",
    "peer",
    "peren",
    "sinaasappel",
    "mandarijn",
    "aardbei",
    "aardbeien",
    "druif",
    "druiven",
    "tomaat",
    "tomaten",
    "komkommer",
    "sla",
    "paprika",
    "ui",
    "uien",
    "knoflook",
    "aardappel",
    "aardappelen",
    "wortel",
    "wortels",
    "courgette",
    "broccoli",
    "bloemkool",
    "fruit",
    "groente",
  ],

  Brood: [
    "brood",
    "bolletje",
    "bolletjes",
    "croissant",
    "stokbrood",
    "wrap",
    "wraps",
    "toast",
    "beschuit",
  ],

  "Koeling en zuivel": [
    "melk",
    "kaas",
    "yoghurt",
    "kwark",
    "boter",
    "room",
    "vla",
    "ei",
    "eieren",
    "zuivel",
  ],

  "Vlees en vis": [
    "kip",
    "gehakt",
    "vlees",
    "vis",
    "zalm",
    "worst",
    "hamburger",
    "spek",
    "tonijn",
  ],

  Ontbijt: [
    "cornflakes",
    "muesli",
    "havermout",
    "ontbijt",
    "jam",
    "hagelslag",
    "pindakaas",
  ],

  "Pasta en rijst": [
    "pasta",
    "spaghetti",
    "macaroni",
    "rijst",
    "noedels",
    "couscous",
  ],

  Conserven: [
    "blik",
    "bonen",
    "mais",
    "maïs",
    "erwten",
    "soep",
    "tomatenblokjes",
  ],

  "Sauzen en kruiden": [
    "saus",
    "ketchup",
    "mayonaise",
    "mosterd",
    "kruiden",
    "zout",
    "peper",
    "olie",
    "azijn",
  ],

  Drinken: [
    "cola",
    "water",
    "sap",
    "limonade",
    "koffie",
    "thee",
    "bier",
    "wijn",
    "drinken",
  ],

  "Snacks en snoep": [
    "chips",
    "snoep",
    "koek",
    "koeken",
    "chocolade",
    "nootjes",
    "popcorn",
    "snack",
  ],

  Diepvries: [
    "diepvries",
    "ijs",
    "pizza",
    "friet",
    "patat",
    "bevroren",
  ],

  Huishouden: [
    "toiletpapier",
    "keukenrol",
    "wasmiddel",
    "afwasmiddel",
    "schoonmaak",
    "vuilniszak",
    "zeep",
    "shampoo",
    "tandpasta",
  ],
};