export const STORAGE_KEY = "SHOPPING_ITEMS";
export const STORE_KEY = "SELECTED_STORE";
export const COUNTRY_STORAGE_KEY = "SORTIT_APP_COUNTRY";
export const DEFAULT_COUNTRY_CODE = "nl";

export const countries = [
  { code: "nl", shortLabel: "NL", label: "Nederland" },
  { code: "be", shortLabel: "BE", label: "België" },
  { code: "de", shortLabel: "DE", label: "Duitsland" },
];

export const getCountryStorageKey = (userId) =>
  `${COUNTRY_STORAGE_KEY}:${userId}`;

export const stores = [
  {
    id: "lidl",
    name: "Lidl",
    countryCodes: ["nl", "de"],
  },
  {
    id: "jumbo",
    name: "Jumbo",
    countryCodes: ["nl"],
  },
  {
    id: "ah",
    name: "Albert Heijn",
    countryCodes: ["nl"],
  },
  {
    id: "plus",
    name: "Plus",
    countryCodes: ["nl"],
  },
  {
    id: "aldi",
    name: "Aldi",
    countryCodes: ["nl", "be", "de"],
  },
  {
    id: "spar",
    name: "Spar",
    countryCodes: ["nl"],
  },
  {
    id: "colruyt",
    name: "Colruyt",
    countryCodes: ["be"],
  },
  {
    id: "delhaize",
    name: "Delhaize",
    countryCodes: ["be"],
  },
  {
    id: "carrefour",
    name: "Carrefour",
    countryCodes: ["be"],
  },
  {
    id: "edeka",
    name: "Edeka",
    countryCodes: ["de"],
  },
  {
    id: "rewe",
    name: "Rewe",
    countryCodes: ["de"],
  },
  {
    id: "kaufland",
    name: "Kaufland",
    countryCodes: ["de"],
  },
];

const GENERAL_STORE_ROUTE = [
  "Groente en fruit",
  "Brood",
  "Vlees en vis",
  "Koeling en zuivel",
  "Ontbijt",
  "Pasta en rijst",
  "Conserven",
  "Sauzen en kruiden",
  "Snacks en snoep",
  "Drinken",
  "Diepvries",
  "Huishouden",
  "Overig",
];

export const storeRoutes = {
  Lidl: [
    "Groente en fruit",
    "Brood",
    "Vlees en vis",
    "Conserven",
    "Pasta en rijst",
    "Sauzen en kruiden",
    "Koeling en zuivel",
    "Diepvries",    
    "Non-food",
    "Snacks en snoep",
    "Dranken",
    "Huishouden",
    "Overig",
  ],

  Jumbo: [
    "Groente en fruit",
    "Vlees en vis",  
    "Brood",
    "Koeling en zuivel",    
    "Ontbijt",
    "Pasta en rijst",    
    "Sauzen en kruiden",
    "Conserven",
    "Snacks en snoep",    
    "Drinken", 
    "Diepvries",
    "Huishouden",
    "Overig",
    "Bloemen en planten"
  ],

  "Albert Heijn": [
    "Groente en fruit",
    "Vlees en vis",
    "Brood", 
    "Koeling en zuivel",
    "Pasta en rijst",
    "Sauzen en kruiden",
    "Conserven",
    "Ontbijt",    
    "Snacks en snoep",
    "Drinken",
    "Diepvries",
    "Huishouden",
    "Overig",
  ],

  Plus: [
    "Brood",
    "Vlees en vis", 
    "Groente en fruit",
    "Snacks en snoep",
    "Ontbijt",
    "Pasta en rijst",
    "Sauzen en kruiden",
    "Conserven",
    "Koeling en zuivel",
    "Drinken",
    "Diepvries",
    "Huishouden",
    "Overig",
  ],

  Aldi: [
    "Groente en fruit",
    "Brood",
    "Ontbijt",
    "Snacks en snoep",
    "Drinken",
    "Pasta, rijst en conserven",
    "Sauzen en kruiden",
    "Koeling en zuivel",
    "Vlees en vis",
    "Diepvries",
    "Huishouden",
    "Overig",
  ],

  Spar: [
    "Groente en fruit", 
    "Koeling en zuivel",
    "Vlees en vis",
    "Brood",
    "Ontbijt",
    "Pasta en rijst",
    "Conserven",
    "Sauzen en kruiden",  
    "Drinken",
    "Diepvries",    
    "Snacks en snoep",
    "Huishouden",
    "Overig",
  ],

  Colruyt: [...GENERAL_STORE_ROUTE],
  Delhaize: [...GENERAL_STORE_ROUTE],
  Carrefour: [...GENERAL_STORE_ROUTE],
  Edeka: [...GENERAL_STORE_ROUTE],
  Rewe: [...GENERAL_STORE_ROUTE],
  Kaufland: [...GENERAL_STORE_ROUTE],
};

export const customStoreCategories = [
  "Groente en fruit",
  "Brood",
  "Vlees en vis",
  "Ontbijt",
  "Pasta en rijst",
  "Conserven",
  "Sauzen en kruiden",
  "Koeling en zuivel",
  "Snacks en snoep",
  "Drinken",
  "Diepvries",
  "Huishouden",
  "Overig",
];

export const categoryIcons = {
  "Groente en fruit": "leaf-outline",
  Brood: "restaurant-outline",
  Ontbijt: "sunny-outline",
  Conserven: "cube-outline",
  "Pasta en rijst": "fast-food-outline",
  "Sauzen en kruiden": "flask-outline",
  Drinken: "water-outline",
  "Snacks en snoep": "ice-cream-outline",
  "Koeling en zuivel": "snow-outline",
  "Vlees en vis": "fish-outline",
  Diepvries: "snow-outline",
  Huishouden: "home-outline",
  Overig: "basket-outline",
};

export const categoryKeywords = {
  "Groente en fruit": [
    "appel",
    "appels",
    "banaan",
    "bananen",
    "peer",
    "peren",
    "sinaasappel",
    "mandarijn",
    "aardbei",
    "aardbeien",
    "druif",
    "druiven",
    "tomaat",
    "tomaten",
    "komkommer",
    "sla",
    "paprika",
    "ui",
    "uien",
    "knoflook",
    "aardappel",
    "aardappelen",
    "wortel",
    "wortels",
    "courgette",
    "broccoli",
    "bloemkool",
    "fruit",
    "groente",
  ],

  Brood: [
    "brood",
    "bolletje",
    "bolletjes",
    "croissant",
    "stokbrood",
    "wrap",
    "wraps",
    "toast",
    "beschuit",
  ],

  "Koeling en zuivel": [
    "melk",
    "kaas",
    "yoghurt",
    "kwark",
    "boter",
    "room",
    "vla",
    "ei",
    "eieren",
    "zuivel",
  ],

  "Vlees en vis": [
    "kip",
    "gehakt",
    "vlees",
    "vis",
    "zalm",
    "worst",
    "hamburger",
    "spek",
    "tonijn",
  ],

  Ontbijt: [
    "cornflakes",
    "muesli",
    "havermout",
    "ontbijt",
    "jam",
    "hagelslag",
    "pindakaas",
  ],

  "Pasta en rijst": [
    "pasta",
    "spaghetti",
    "macaroni",
    "rijst",
    "noedels",
    "couscous",
  ],

  Conserven: [
    "blik",
    "bonen",
    "mais",
    "maïs",
    "erwten",
    "soep",
    "tomatenblokjes",
  ],

  "Sauzen en kruiden": [
    "saus",
    "ketchup",
    "mayonaise",
    "mosterd",
    "kruiden",
    "zout",
    "peper",
    "olie",
    "azijn",
  ],

  Drinken: [
    "cola",
    "water",
    "sap",
    "limonade",
    "koffie",
    "thee",
    "bier",
    "wijn",
    "drinken",
  ],

  "Snacks en snoep": [
    "chips",
    "snoep",
    "koek",
    "koeken",
    "chocolade",
    "nootjes",
    "popcorn",
    "snack",
  ],

  Diepvries: [
    "diepvries",
    "ijs",
    "pizza",
    "friet",
    "patat",
    "bevroren",
  ],

  Huishouden: [
    "toiletpapier",
    "keukenrol",
    "wasmiddel",
    "afwasmiddel",
    "schoonmaak",
    "vuilniszak",
    "zeep",
    "shampoo",
    "tandpasta",
  ],
};
